apiVersion: apps/v1
kind: Deployment
metadata:
  name: aitestmate-embeddings
  labels:
    # {{ include "aitestmate-embeddings.labels" . | nindent 4 }}
spec:
  replicas:
    {{ .Values.replicaCount }}
  selector:
    matchLabels:
      # {{ include "aitestmate-embeddings.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      # {{ with .Values.podAnnotations }}
      annotations:
        # {{ toYaml . | nindent 8 }}
      # {{ end }}
      labels:
        # {{ include "aitestmate-embeddings.labels" . | nindent 8 }}
        # {{ with .Values.podLabels }}
        # {{ toYaml . | nindent 8 }}
        # {{ end }}
    spec:
      # {{ with .Values.imagePullSecrets }}
      imagePullSecrets:
        # {{ toYaml . | nindent 8 }}
      # {{ end }}
      automountServiceAccountToken: false
      # {{ with .Values.podSecurityContext }}
      securityContext:
        # {{ toYaml . | nindent 8 }}
      # {{ end }}
      containers:
        - name: aitestmate-embeddings
          # {{ with .Values.securityContext }}
          securityContext:
            # {{ toYaml . | nindent 12 }}
          # {{ end }}
          image: >-
            {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: >-
            {{ .Values.image.pullPolicy }}
          args: ["--host", "0.0.0.0"]
          ports:
            - name: http
              containerPort:
                {{ .Values.service.port }}
              protocol: TCP
          # {{ with (concat (default list .Values.env) (default list .Values.extraEnv) | uniq) }}
          env:
            # {{ toYaml . | nindent 12 }}
          # {{ end }}
          # {{ with .Values.startupProbe }}
          startupProbe:
            # {{ toYaml . | nindent 12 }}
          # {{ end }}
          # {{ with .Values.livenessProbe }}
          livenessProbe:
            # {{ toYaml . | nindent 12 }}
          # {{ end }}
          # {{ with .Values.readinessProbe }}
          readinessProbe:
            # {{ toYaml . | nindent 12 }}
          # {{ end }}
          # {{ with .Values.resources }}
          resources:
            # {{ toYaml . | nindent 12 }}
          # {{ end }}
          # {{ with .Values.volumeMounts }}
          volumeMounts:
            # {{ toYaml . | nindent 12 }}
          # {{ end }}
      # {{ with .Values.volumes }}
      volumes:
        # {{ toYaml . | nindent 8 }}
      # {{ end }}
      # {{ with .Values.nodeSelector }}
      nodeSelector:
        # {{ toYaml . | nindent 8 }}
      # {{ end }}
      # {{ with .Values.affinity }}
      affinity:
        # {{ toYaml . | nindent 8 }}
      # {{ end }}
      # {{ with .Values.tolerations }}
      tolerations:
        # {{ toYaml . | nindent 8 }}
      # {{ end }}
