apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.neo4j.ports.http }}
      targetPort: http
      name: http
    - port: {{ .Values.neo4j.ports.bolt }}
      targetPort: bolt
      name: bolt
  selector:
    app: {{ .Release.Name }}
